from fpdf import FPDF
import re


def add_glossary_page(pdf):
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Legal Glossary & Concepts", ln=True, align='C')
    pdf.ln(5)

    glossary = {
        "GDPR": "General Data Protection Regulation. The global gold standard for data privacy and user rights.",
        "PECA": "Prevention of Electronic Crimes Act. Focused on cybersecurity, unauthorized access, and data integrity.",
        "RAG": "Retrieval-Augmented Generation. The AI technology used here to ensure accuracy by reading real documents.",
        "Gap Analysis": "The process of identifying what is missing in a Policy compared to a Law.",
        "Data Minimization": "The principle that companies should only collect the data absolutely necessary for their service.",
        "Risk Score": "A calculated metric (0-100) based on a strict legal rubric to identify liability."
    }

    for term, definition in glossary.items():
        pdf.set_font("Arial", 'B', 12)
        pdf.set_text_color(0, 0, 100)
        pdf.cell(0, 8, f"{term}:", ln=True)
        pdf.set_font("Arial", '', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 7, definition)
        pdf.ln(2)


def add_disclaimer(pdf):
    pdf.ln(10)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)

    disclaimer_text = (
        "DISCLAIMER: This report is generated by an Artificial Intelligence system and is intended "
        "for informational purposes only. It does not constitute formal legal advice. Please consult "
        "with a qualified legal professional before making compliance decisions."
    )

    pdf.multi_cell(0, 5, disclaimer_text, border=1, align='C', fill=True)


def clean_text_for_pdf(text):
    # Remove null bytes explicitly
    text = text.replace('\x00', '')
    # Keep only tab, newline, carriage return, and printable ASCII (0x20-0x7E)
    text = re.sub(r'[^\x09\x0A\x0D\x20-\x7E]', '', text)
    return text


def create_pdf_report(report_text):
    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # 1. Header
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 15, txt="Compliance Audit Report", ln=True, align='C')
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, 25, 200, 25)
    pdf.ln(10)

    # 2. Clean text thoroughly (null bytes + non-printable chars)
    clean_text = clean_text_for_pdf(report_text)

    # 3. Body Text Processing
    for line in clean_text.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        if any(h in line.upper() for h in [":", "STEP", "RISK"]):
            pdf.set_font("Arial", 'B', 11)
            pdf.set_text_color(0, 0, 100)
        else:
            pdf.set_font("Arial", '', 11)
            pdf.set_text_color(0, 0, 0)

        pdf.multi_cell(0, 7, txt=line, align='L')
        pdf.ln(1)

    # 4. Glossary & Disclaimer pages
    add_glossary_page(pdf)
    add_disclaimer(pdf)

    # 5. Return as bytes (required by st.download_button)
    return bytes(pdf.output(dest='S'))
