from fpdf import FPDF
import re

def create_pdf_report(report_text):
    # Standard A4 Setup
    pdf = FPDF(orientation='P', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # 1. Header
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 15, txt="Compliance Audit Report", ln=1, align='C')
    pdf.set_draw_color(200, 200, 200) 
    pdf.line(10, 25, 200, 25) 
    pdf.ln(10)

    # 2. Text Cleaning
    clean_text = re.sub(r'[^\x00-\x7f]', r'', report_text)

    # 3. Body Text Processing
    for line in clean_text.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        if any(h in line.upper() for h in [":", "STEP", "RISK"]):
            pdf.set_font("Arial", 'B', 11)
            pdf.set_text_color(0, 0, 100) 
        else:
            pdf.set_font("Arial", '', 11)
            pdf.set_text_color(0, 0, 0) 

        pdf.multi_cell(0, 7, txt=line, align='L')
        pdf.ln(1)

    # 4. ADD DISCLAIMER (Added here to avoid errors)
    pdf.ln(10)
    pdf.set_fill_color(245, 245, 245)  
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)
    
    disclaimer_text = (
        "DISCLAIMER: This report is generated by an Artificial Intelligence system and is intended "
        "for informational purposes only. It does not constitute formal legal advice. Please consult "
        "with a qualified legal professional before making compliance decisions."
    )
    pdf.multi_cell(0, 5, txt=disclaimer_text, border=1, align='C', fill=True)

    # 5. Output
    # If you use the 'with open' logic in app.py, keep this as is:
    report_path = "audit_report.pdf"
    pdf.output(report_path)
    return report_path
